### ISSUE TITLE
Response with status 500 and blocking send_request if sm59 configuration not set to SSL

### ISSUE THREAD

**Issue by hf-kklein** [microsoft/ABAP-SDK-for-Azure#44]
I'm using the ABAP SDK for Azure for sending data to an event hub.

The [documentation](https://github.com/microsoft/ABAP-SDK-for-Azure/blob/master/ABAP%20SDK%20Implementation%20Guide%20for%20Azure%20Event%20hubs.pdf) clearly describes how to configure the remote target (page 12 as of today):
![grafik](https://user-images.githubusercontent.com/23094997/68282963-ee2a9680-007a-11ea-8fe6-bf6e34589669.png)

However, if this configuration is wrong (SSL set to "inactive"). This configuration error is not catched by the ABAP SDK but instead the sending process
```
CALL METHOD oref_eventhub->send
  EXPORTING
     request        = lv_xstring  "Input XSTRING of SAP Business Event data
     it_headers     = it_headers  "Header attributes
   IMPORTING
     response       = lv_response       "Response from EventHub
     ev_http_status = lv_http_status.   "Status
```

in synchronous, retry active mode (see table `ZADF_CONFIG`) is blocking the debugger for ~1 minute in my case. There is no exception thrown but the HTTP status code in `lv_http_status` is 500. The response body is empty. Took me quite a while, to find my own error. Maybe we could handle this edge case in the code.

**Comment by krdash** [comment]
Hello @hf-kklein - Thanks for your valuable feedback. we are in the process of doing this configuration error check during manual configuration of interface ID in table ZADF_CONFIG as a part of Table events where FM :RFC_READ_HTTP_DESTINATION is used for validation.
so that it would pop up a error message for doing the correct configuration of 'SSL set to Active'. We would keep you posted once this check is in place and changes are commited in master branch. 
![image](https://user-images.githubusercontent.com/38972371/68290741-77a78c00-00ae-11ea-91d1-1dc572ecfd27.png)
Thanks,
Krishna

**Comment by gregorwolf** [comment]
Hi @krdash ,
where you able to implement the correction or do you need external help?

**Comment by krdash** [comment]
Hi @gregorwolf - Please help in implementing the correction. Thank you for your contribution in advance. Regards,
Krishna
