### ISSUE TITLE
Follow-up on deletion of logs (table ZREST_MO_PAYLOAD is growing very fast)

### ISSUE THREAD

**Issue by netweaver-abap-sdk-user1** [microsoft/ABAP-SDK-for-Azure#69]
Hi,

We do not have issues on executing the programs for deletion (ZREST_MONITOR_ARCHIVE  and ZREST_TABLES_ARCHIVE) and it seems to work okay. Thanks.

However, we would like to ask if there are any options for the log not to write to ZREST_MO_PAYLOAD table? That is, we prefer to have the log entries but not the payload.

Thanks again,
Allaine

**Comment by krdash** [comment]
Hi Allaine, @netweaver-abap-sdk-user1 @microsoft/abapsdk,
Thanks for reaching out to us on your query.
The functionality to populate table ZREST_MO_PAYLOAD  with payload is to provide an manual reprocessing mechanism( Tcode ZREST_UTIL) and automatic reprocessing through batch job program 'ZREST_SCHEDULER' which is part of ZREST package. This feature is needed to allow reprocessing using the same payload in case of failure http status. Please let us know in case we need to provide any other information. Thanks, Krishna

**Comment by netweaver-abap-sdk-user1** [comment]
Hi,

We agree that the feature is needed to allow reprocessing using the same payload in-case of failure http status.  However, we thought that we understood that the feature is only activated when the table ZADF_CONFIG reprocessing flag is set to "Enable Reprocessing".  If the entry is blank (or that it's a No), then why is there a need to populate the table ZREST_MO_PAYLOAD? 

That is, can the reprocessing flag on the table ZADF_CONFIG act as the switch to populate the ZREST_MO_PAYLOAD table?

Thanks,
Allaine

**Comment by krdash** [comment]
Hello Allaine,
Thanks for your valuable feedback.
Current version of SDK doesn't include this relation of Table Field IS_TRY value 'Enable Reprocessing' to updating of logging of all ZREST related tables. It is always recommended to use this field value as blank , so that there would always be unique message ID which can be assigned to a http request service call.  We will also update our implementation guide with some note for this to avoid any confusion.
And We will be looking into this as a part of our backlog work items for future release. If you could contribute and commit the code changes in our repository, that would also be great. Please share your thoughts.
Thanks , 
Krishna

**Comment by vikasbansal2022** [comment]
Hello @Allaine

Thanks for reaching out. We are planning to hide the IS_TRY column to avoid any confusion. Since Retry functionality is not dependent on that and there will be additional functionality/Authorization for user to be allowed to see /Download payload in the ZREST_UTIL.

Regards,
Vikas
