### ISSUE TITLE
Syntax error in class ZCL_ADF_SERVICE_FACTORY

### ISSUE THREAD

**Issue by RohanAccenture** [microsoft/ABAP-SDK-for-Azure#72]
Hi Team,

We are getting error of Method "GET_CLASSNAME" is unknown or PROTECTED or PRIVATE in class ZCL_ADF_SERVICE_FACTORY.

**Comment by krdash** [comment]
Hello @RohanAccenture - Thanks for reaching out to us on your query. I think your SAP system Netweaver version is less than 7.4 and this might be causing this syntax issue due to below inline declaration statement in method 'CREATE' of class 'ZCL_ADF_SERVICE_FACTORY'.
DATA(classname) = m_service_config->get_classname( i_interface_type = interface_type ).

Also, I checked that current version of SDK includes method 'GET_CLASS' which exists as a part of interface 'ZIF_ADF_AZURE_DEFCONFIG' and its been implemented in class 'zcl_adf_service_default_config'. 

We are trying to replicate the issue in our environment.
Meanwhile please could you try to fix this syntax error by declaring the variable 'class' as shown below and check if it resolves the issue.

Data classname type SEOCLNAME.
classname = m_service_config->get_classname( i_interface_type = interface_type ).

Thanks,
Krishna Chandra Dash

**Comment by RohanAccenture** [comment]
Hi @krdash, 
we tried with the suggested code but still getting the error of Method "GET_CLASSNAME" is unknown or PROTECTED or PRIVATE.

Also, we are using S/4 1809 system so netweaver > 7.4 .

Attached screenshot for your reference. 
![image](https://user-images.githubusercontent.com/62287859/80212898-f6d94e00-8655-11ea-9831-de4499eeb928.png)

![image](https://user-images.githubusercontent.com/62287859/80212958-12445900-8656-11ea-8b2c-a798de820991.png)

**Comment by krdash** [comment]
Hi @RohanAccenture - If your SAP systems Netweaver system > 4.7 , then you shouldn't face this issue. However please could you check the attribute 'm_service_config' whether its referring to object reference type interface 'ZIF_ADF_AZURE_DEFCONFIG' under attribute section of class 'ZCL_ADF_SERVICE_FACTORY'.  Also, please check the alias section and method section of implementation class 'zcl_adf_service_default_config'.

Please share the screen shot for further trouble shooting as we don't see any issue in our environment. 

Thanks,
Krishna

**Comment by RohanAccenture** [comment]
Hi,

PFB the screenshots :-

![image](https://user-images.githubusercontent.com/62287859/80348124-efe75100-888a-11ea-9804-67937d769c68.png)

![image](https://user-images.githubusercontent.com/62287859/80348167-02fa2100-888b-11ea-974d-c23cb9c90abe.png)

![image](https://user-images.githubusercontent.com/62287859/80348196-0e4d4c80-888b-11ea-8d64-1cdc00cdf474.png)

**Comment by krdash** [comment]
Hi @RohanAccenture - Thanks for sharing the screen shots. As per current version of SDK, the attribute 'm_service_config' has been declared as 'Private' (please check below screen shot) . I think your code base is not in sync with the current version of SDK. Please could you sync up the changes again from our master branch code repository. It should resolve the issue.

and Also, please try to check once by changing the declaration as 'Private' for attribute 'm_service_config' of class 'zcl_adf_service_factory' before the sync up just to check if its working or not.

![image](https://user-images.githubusercontent.com/38972371/80349718-45246200-888d-11ea-8a0d-1e5a78003987.png)

**Comment by RohanAccenture** [comment]
Hi ,
we tried changing the M_SERVICE_CONFIG visibility from PUBLIC to PRIVATE but still we are getting the same error. We checked the source code on GIT. It is exactly the same in our system. We could not find any relevant code related to GET_CLASSNAME method in the SRC repository.

**Comment by krdash** [comment]
Hi @RohanAccenture - Please find below screenshot of our current Source code repository in Github , which includes implementation of method 'GET_CLASSNAME ' in implementation class 'ZCL_ADF_SERVICE_DEFAULT_CONFIG'  for file 'zcl_adf_service_default_config.clas.abap' under ZADF folder. 

![image](https://user-images.githubusercontent.com/38972371/80373513-cd692e00-88b2-11ea-8882-aee2c3279990.png)

And as per the initial snapshots provided by you, attribute 'm_service_config' was declared as 'Public' which means that code base is not in sync with our source code repository as it was supposed to be reflected as 'Private' as per current code base in Github source code repository.
  
Request you to validate and refer the corresponding .class.abap file in our source code repository if there is any difference and try to pull the latest changes again into your system . If the issue still persists, please reach out to our team ABAP SDK for Azure <abapsdk4azure@microsoft.com> from your mail id, so that we can have quick trouble shooting session for resolving the issue. 

Meanwhile please try to validate once as per below screen shots if it can help you to resolve the issue.
![image](https://user-images.githubusercontent.com/38972371/80373618-f4276480-88b2-11ea-9b26-857d47028d66.png)

![image](https://user-images.githubusercontent.com/38972371/80373632-fb4e7280-88b2-11ea-9694-b36d47fd15d7.png)

![image](https://user-images.githubusercontent.com/38972371/80373655-01dcea00-88b3-11ea-9bbd-ece1cc1c3805.png)

![image](https://user-images.githubusercontent.com/38972371/80373668-07d2cb00-88b3-11ea-9654-2c3d8ba14bc8.png)

![image](https://user-images.githubusercontent.com/38972371/80373690-0f926f80-88b3-11ea-9113-c2e985709170.png)

Thanks,
Krishna

**Comment by RohanAccenture** [comment]
Hi Krishna,

We are getting the following error while pulling the code as well as we get the message : 'Dynpro ZREST_SCREEN 0100 was activated'.

Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 

Import of object ZCL_ADF_SERVICE failed 

Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 

Import of object ZCL_ADF_SERVICE_AAD failed 

Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 

Import of object ZCL_ADF_SERVICE_BLOB failed 

Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 

Import of object ZCL_ADF_SERVICE_COSMOSDB failed 

Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 

Import of object ZCL_ADF_SERVICE_EVENTHUB failed 

Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 

Import of object ZCL_ADF_SERVICE_KEYVAULT failed 

Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 

Import of object ZCL_ADF_SERVICE_OMS_LA failed 

Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 

Import of object ZCL_ADF_SERVICE_SERVICEBUS failed 

Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 

Import of object ZCL_REST_FRAMEWORK failed 

Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 

Import of object ZCL_REST_UTILITY_CLASS failed 

Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 

Import of object ZCX_ADF_SERVICE failed 

Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 

Import of object ZCX_ADF_SQLDB failed 

Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 

Import of object ZCX_HTTP_CLIENT_FAILED failed 

Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 

Import of object ZCX_INTERACE_CONFIG_MISSING failed 

Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 

Import of object ZCX_REST failed 

Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5 

Import of object Z_RESTCALL_FROM_DB failed 

Error from SEO_INTERFACE_CREATE_COMPLETE. Subrc = 5 

Import of object ZIF_ADF_AZURE_DEFCONFIG failed 

Error from SEO_INTERFACE_CREATE_COMPLETE. Subrc = 5 

Import of object ZIF_REST_FRAMEWORK failed 

Error from SEO_INTERFACE_CREATE_COMPLETE. Subrc = 5 

Import of object ZIF_REST_HTTP_CONSTANTS failed

**Comment by krdash** [comment]
Hi @RohanAccenture - Please could you let us know if you are using 'Online' option of ZABAPGit for pulling the latest changes? 
and please reach out to our team ABAP SDK for Azure abapsdk4azure@microsoft.com from your mail id, so that we can have quick trouble shooting session for resolving the issue.
Thanks,
Krishna

**Comment by RohanAccenture** [comment]
Hi Krishna,

We have reached out to ABAP SDK for Azure team, Waiting for their response.

**Comment by krdash** [comment]
Thanks @RohanAccenture for reaching out to us .
We are going to schedule a quick troubleshooting session for tomorrow in India Time. Hope this time would work for your team.
Thanks,
Krishna

**Comment by krdash** [comment]
Hi @RohanAccenture - We tried to replicate the issue by pulling the latest changes into one of our system and we didn't get any error . However we came to know that the issue related to these errors might be due to objects locked in multiple Transport requests/Tasks.

Please could you check once and unlock your existing open Transports/Tasks containing SDK objects before pulling latest changes through ZABAPGit. Hope this would resolve your issue.

'Error from SEO_CLASS_CREATE_COMPLETE. Subrc = 5'
'Import of object ZCL_REST_UTILITY_CLASS failed' 

Hi Lars @larshp- Please suggest us if there is any alternate way to fix this object locking issues.

Thanks,
Krishna

**Comment by RohanAccenture** [comment]
Hi Krishna,

Thanks for your support. We were able to deploy the SDK on our system after changing the package of required objects. We are able to send data from SAP to Azure EventHub.

We can see 1 message received in Eventhub but not sure how to check what data is received. Could you please help us with this.

**Comment by RohanAccenture** [comment]
Thanks for your support.
