### ISSUE TITLE
Getting message “Error in importing encoded SAS KEY value for ADB2CTOKEN” when starting the report “ZADF_DEMO_AZURE_GRAPH” – different than issues #97 and #48?

### ISSUE THREAD

**Issue by iloveabap** [microsoft/ABAP-SDK-for-Azure#98]
Hi,
I’m trying to start the report zadf_demo_azure_graph. I used this documentation: ABAP-SDK-for-Azure/src/zadf/zadf_graph at master · microsoft/ABAP-SDK-for-Azure (github.com). When I’m starting the report, I always get the error message “Error in importing encoded SAS KEY value for ADB2CTOKEN”. 
Inspecting the code, I found an import in the class ZCL_ADF_SERVICE. 

      IMPORT tab  = lt_enveloped_data[]
             FROM DATABASE zadf_con_indx(zd)
             TO lw_indx
             ID lv_srtfd.
      IF NOT lt_enveloped_data[] IS INITIAL.

Debugging the code lt_enveloped_data[] is always empty. In the result an exception was called.  Looking for an export to fill zadf_con_indx I found nothing.
Perhaps the solution of my error is in issue #97 and #48 but I didn’t understand it. Could it be possible that the issues #97 and #48 handling another situation? 
What am I doing wrong? Can someone help?

Regards 
Henning

**Comment by leofrederiksen** [comment]
Hi Henning
The transfer of data to Event Hub is working without errors for us as long as we dont have parallel processes trying to read the SAS Key/Token.
We are using SLT SDK to move all table changes to Azure, and SLT has to use parallel processes, otherwise the system will not be able to keep up with all the changes made in SAP.
The SLT feature is actually part of S4 Core systems (installed by default).
We are still trying to understand the error we have with the Azure SDK as it seems to be a design flaw.

**Comment by vikasbansal2022** [comment]
Hi @iloveabap 
The index table ZADF_CON_INDX is filled with encrypted key when maintaining the entry in table ZADF_CONFIG via TMG events based on interface ID. 

Please let us know if you still facing this problem. we can have a look at it. 

Regards,
Vikas

**Comment by leofrederiksen** [comment]
> 
Hi Vikas
I notived you closed this one, and I am unsure how to proceed. We have been searching for other tools to get data from SAP into Azure, but I really like this interface.
Anyway possible to have a view at it together?
Issue #48 mention something about it, but I dont understand the core idea:
"To be honest, we have not yet tried parallel loads using SLT SDK, however, the way we have treated the authentication is by using a Managed Identity and generating an access token from Azure AD.
We then stored this access token in SLT cluster memory since it expires after every 24 hours, with each data transfer, we retrieve the access token if within 23 hours else generate a new one and store it again."

**Comment by vikasbansal2022** [comment]
Thanks @leofrederiksen for reaching out.

I will be happy to connect. Please share you email ID will setup call with you.

Regards,
Vikas

**Comment by leofrederiksen** [comment]
Thanks, leo.frederiksen2@nttdata.com

**Comment by vikasbansal2022** [comment]
Thanks Leo 

Will be addressing this in issue # Error in Importing SAS Key #97

Regards,
Vikas
