### ISSUE TITLE
Deprecation of Azure AD Graph API in June 2022

### ISSUE THREAD

**Issue by CONCETO-flow** [microsoft/ABAP-SDK-for-Azure#99]
Hi,

will this project here be migrated to the Microsoft Graph API?
The Azure AD Graph API is now for longer on the deprecation path and its final date is end of June 2022.

https://docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-faq#:~:text=The%20Azure%20AD%20Graph%20API,resilient%20than%20Azure%20AD%20Graph.

Best regards,
Florian

**Comment by Sanjukum19** [comment]
Hi Florian,

The Graph objects here in the repo will allow you to call Microsoft Graph API. However, please ensure the below points for the same such as:
- Relevant Microsoft Graph API permissions are added for AAD registered app.
- Kindly use resource graph.microsoft.com (for AAD v1.0 token) & scope as graph.microsoft.com/.default (for AAD v2.0) instead of graph.windows.net.
- Graph request URI should be pointing to v1.0 endpoint e.g., 'https://graph.microsoft.com/v1.0/users'.

Kindly let us know in case of any concerns.

Best Regards,
Sanju

**Comment by Sanjukum19** [comment]
Hi Florian,

Hope we have addressed your query. We are closing this issue.

Thanks,
Sanju
